Python 3.14.3 (tags/v3.14.3:323c59a, Feb  3 2026, 16:04:56) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> # ejercicio 5: prueba de escritorio
... 
... suma = 0
... x = 20
... 
... suma = suma + x
... y = 40
... 
... # x es igual a x más y al cuadrado
... x = x + (y ** 2)
... 
... # suma es igual a suma más x dividido y
... suma = suma + (x / y)
... 
